services:
  redis-insight:
    image: redis/redisinsight:3.8.0
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_insight_data:
